#version: '2'
#services:
#  apache:
#    image: 'dpage/pgadmin4'
#    environment:
#     - PGADMIN_DEFAULT_EMAIL=user@domain.com
#     - PGADMIN_DEFAULT_PASSWORD=admin1234
#    ports:
#      - '5050:80'
version: '3'

services:
#  teste-postgres-compose:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: "Postgres2019!"
#    ports:
#      - "15432:5432"
#    volumes:
#      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
#    networks:
#      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "renatogroff@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "5050:80"
      - "5432:5432"
        #depends_on:
        #- teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
